version: '3'

services:
  frontend:
    image: httpd:2.4

    # for development env
    volumes:
      - ./frontend/:/usr/local/apache2/htdocs/
    ports:
      - '5000:80'

  microservices:
    build: ./microservices
    command: npm start
    volumes:
      - ./microservices:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:8080"